# Generated by Django 4.2.13 on 2024-05-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events_listing", "0003_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_on"]},
        ),
        migrations.AlterModelOptions(
            name="postevent",
            options={"ordering": ["date"]},
        ),
    ]
