# Generated by Django 4.2.13 on 2024-05-28 07:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events_listing", "0005_eventsignup"),
    ]

    operations = [
        migrations.AddField(
            model_name="postevent",
            name="featured_image",
            field=cloudinary.models.CloudinaryField(
                default="placeholder", max_length=255, verbose_name="image"
            ),
        ),
    ]
